#############################################################################
# Makefile for building: entomologist
# Generated by qmake (2.01a) (Qt 4.6.3) on: Mon Mar 14 17:08:05 2011
# Project:  Entomologist.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile Entomologist.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DAPP_VERSION=\"0.4\" -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtSql -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lqjson -lQtSql -L/usr/lib64 -lQtXml -lQtGui -L/usr/X11R6/lib64 -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MainWindow.cpp \
		libmaia/maiaXmlRpcServerConnection.cpp \
		libmaia/maiaXmlRpcServer.cpp \
		libmaia/maiaXmlRpcClient.cpp \
		libmaia/maiaObject.cpp \
		libmaia/maiaFault.cpp \
		trackers/Backend.cpp \
		trackers/Bugzilla.cpp \
		NewTracker.cpp \
		trackers/NovellBugzilla.cpp \
		Autodetector.cpp \
		SqlBugModel.cpp \
		SqlBugDelegate.cpp \
		CommentFrame.cpp \
		UploadDialog.cpp \
		Preferences.cpp \
		About.cpp \
		SqlWriterThread.cpp \
		SqlWriter.cpp \
		PlaceholderLineEdit.cpp \
		qtsoap/qtsoap.cpp \
		trackers/Mantis.cpp \
		ChangelogWindow.cpp \
		ChangelogListDelegate.cpp \
		trackers/Launchpad.cpp moc_MainWindow.cpp \
		moc_maiaXmlRpcServerConnection.cpp \
		moc_maiaXmlRpcServer.cpp \
		moc_maiaXmlRpcClient.cpp \
		moc_maiaObject.cpp \
		moc_maiaFault.cpp \
		moc_Backend.cpp \
		moc_Bugzilla.cpp \
		moc_NewTracker.cpp \
		moc_NovellBugzilla.cpp \
		moc_Autodetector.cpp \
		moc_SqlBugModel.cpp \
		moc_SqlBugDelegate.cpp \
		moc_CommentFrame.cpp \
		moc_UploadDialog.cpp \
		moc_Preferences.cpp \
		moc_About.cpp \
		moc_SqlWriterThread.cpp \
		moc_SqlWriter.cpp \
		moc_PlaceholderLineEdit.cpp \
		moc_qtsoap.cpp \
		moc_Mantis.cpp \
		moc_ChangelogWindow.cpp \
		moc_Launchpad.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		MainWindow.o \
		maiaXmlRpcServerConnection.o \
		maiaXmlRpcServer.o \
		maiaXmlRpcClient.o \
		maiaObject.o \
		maiaFault.o \
		Backend.o \
		Bugzilla.o \
		NewTracker.o \
		NovellBugzilla.o \
		Autodetector.o \
		SqlBugModel.o \
		SqlBugDelegate.o \
		CommentFrame.o \
		UploadDialog.o \
		Preferences.o \
		About.o \
		SqlWriterThread.o \
		SqlWriter.o \
		PlaceholderLineEdit.o \
		qtsoap.o \
		Mantis.o \
		ChangelogWindow.o \
		ChangelogListDelegate.o \
		Launchpad.o \
		moc_MainWindow.o \
		moc_maiaXmlRpcServerConnection.o \
		moc_maiaXmlRpcServer.o \
		moc_maiaXmlRpcClient.o \
		moc_maiaObject.o \
		moc_maiaFault.o \
		moc_Backend.o \
		moc_Bugzilla.o \
		moc_NewTracker.o \
		moc_NovellBugzilla.o \
		moc_Autodetector.o \
		moc_SqlBugModel.o \
		moc_SqlBugDelegate.o \
		moc_CommentFrame.o \
		moc_UploadDialog.o \
		moc_Preferences.o \
		moc_About.o \
		moc_SqlWriterThread.o \
		moc_SqlWriter.o \
		moc_PlaceholderLineEdit.o \
		moc_qtsoap.o \
		moc_Mantis.o \
		moc_ChangelogWindow.o \
		moc_Launchpad.o \
		qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Entomologist.pro
QMAKE_TARGET  = entomologist
DESTDIR       = 
TARGET        = entomologist

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_MainWindow.h ui_NewTracker.h ui_CommentFrame.h ui_UploadDialog.h ui_Preferences.h ui_About.h ui_ChangelogWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Entomologist.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtSql.prl \
		/usr/lib64/libQtCore.prl \
		/usr/lib64/libQtXml.prl \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtNetwork.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile Entomologist.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtSql.prl:
/usr/lib64/libQtCore.prl:
/usr/lib64/libQtXml.prl:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile Entomologist.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/entomologist0.4 || $(MKDIR) .tmp/entomologist0.4 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/entomologist0.4/ && $(COPY_FILE) --parents MainWindow.h libmaia/maiaXmlRpcServerConnection.h libmaia/maiaXmlRpcServer.h libmaia/maiaXmlRpcClient.h libmaia/maiaObject.h libmaia/maiaFault.h trackers/Backend.h trackers/Bugzilla.h NewTracker.h trackers/NovellBugzilla.h Autodetector.h SqlBugModel.h SqlBugDelegate.h CommentFrame.h UploadDialog.h Preferences.h About.h SqlWriterThread.h SqlWriter.h PlaceholderLineEdit.h qtsoap/qtsoap.h trackers/Mantis.h ChangelogWindow.h ChangelogListDelegate.h trackers/Launchpad.h .tmp/entomologist0.4/ && $(COPY_FILE) --parents resources.qrc .tmp/entomologist0.4/ && $(COPY_FILE) --parents main.cpp MainWindow.cpp libmaia/maiaXmlRpcServerConnection.cpp libmaia/maiaXmlRpcServer.cpp libmaia/maiaXmlRpcClient.cpp libmaia/maiaObject.cpp libmaia/maiaFault.cpp trackers/Backend.cpp trackers/Bugzilla.cpp NewTracker.cpp trackers/NovellBugzilla.cpp Autodetector.cpp SqlBugModel.cpp SqlBugDelegate.cpp CommentFrame.cpp UploadDialog.cpp Preferences.cpp About.cpp SqlWriterThread.cpp SqlWriter.cpp PlaceholderLineEdit.cpp qtsoap/qtsoap.cpp trackers/Mantis.cpp ChangelogWindow.cpp ChangelogListDelegate.cpp trackers/Launchpad.cpp .tmp/entomologist0.4/ && $(COPY_FILE) --parents MainWindow.ui NewTracker.ui CommentFrame.ui UploadDialog.ui Preferences.ui About.ui ChangelogWindow.ui .tmp/entomologist0.4/ && $(COPY_FILE) --parents entomologist_en.ts .tmp/entomologist0.4/ && (cd `dirname .tmp/entomologist0.4` && $(TAR) entomologist0.4.tar entomologist0.4 && $(COMPRESS) entomologist0.4.tar) && $(MOVE) `dirname .tmp/entomologist0.4`/entomologist0.4.tar.gz . && $(DEL_FILE) -r .tmp/entomologist0.4


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


distfile:
	mkdir -p .tmp/entomologist-0.4 && cp -r -f --parent main.cpp MainWindow.cpp libmaia/maiaXmlRpcServerConnection.cpp libmaia/maiaXmlRpcServer.cpp libmaia/maiaXmlRpcClient.cpp libmaia/maiaObject.cpp libmaia/maiaFault.cpp trackers/Backend.cpp trackers/Bugzilla.cpp NewTracker.cpp trackers/NovellBugzilla.cpp Autodetector.cpp SqlBugModel.cpp SqlBugDelegate.cpp CommentFrame.cpp UploadDialog.cpp Preferences.cpp About.cpp SqlWriterThread.cpp SqlWriter.cpp PlaceholderLineEdit.cpp qtsoap/qtsoap.cpp trackers/Mantis.cpp ChangelogWindow.cpp ChangelogListDelegate.cpp trackers/Launchpad.cpp MainWindow.h libmaia/maiaXmlRpcServerConnection.h libmaia/maiaXmlRpcServer.h libmaia/maiaXmlRpcClient.h libmaia/maiaObject.h libmaia/maiaFault.h trackers/Backend.h trackers/Bugzilla.h NewTracker.h trackers/NovellBugzilla.h Autodetector.h SqlBugModel.h SqlBugDelegate.h CommentFrame.h UploadDialog.h Preferences.h About.h SqlWriterThread.h SqlWriter.h PlaceholderLineEdit.h qtsoap/qtsoap.h trackers/Mantis.h ChangelogWindow.h ChangelogListDelegate.h trackers/Launchpad.h MainWindow.ui NewTracker.ui CommentFrame.ui UploadDialog.ui Preferences.ui About.ui ChangelogWindow.ui resources.qrc COPYING Entomologist.pro README INSTALL *.qm *.ts entomologist.desktop entomologist.spec graphics/ install_icons/ libmaia/ .tmp/entomologist-0.4 && cd .tmp && tar cvzf entomologist-0.4\.tar.gz entomologist-0.4 && mv entomologist-0.4\.tar.gz .. && cd ..

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MainWindow.cpp moc_maiaXmlRpcServerConnection.cpp moc_maiaXmlRpcServer.cpp moc_maiaXmlRpcClient.cpp moc_maiaObject.cpp moc_maiaFault.cpp moc_Backend.cpp moc_Bugzilla.cpp moc_NewTracker.cpp moc_NovellBugzilla.cpp moc_Autodetector.cpp moc_SqlBugModel.cpp moc_SqlBugDelegate.cpp moc_CommentFrame.cpp moc_UploadDialog.cpp moc_Preferences.cpp moc_About.cpp moc_SqlWriterThread.cpp moc_SqlWriter.cpp moc_PlaceholderLineEdit.cpp moc_qtsoap.cpp moc_Mantis.cpp moc_ChangelogWindow.cpp moc_Launchpad.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_maiaXmlRpcServerConnection.cpp moc_maiaXmlRpcServer.cpp moc_maiaXmlRpcClient.cpp moc_maiaObject.cpp moc_maiaFault.cpp moc_Backend.cpp moc_Bugzilla.cpp moc_NewTracker.cpp moc_NovellBugzilla.cpp moc_Autodetector.cpp moc_SqlBugModel.cpp moc_SqlBugDelegate.cpp moc_CommentFrame.cpp moc_UploadDialog.cpp moc_Preferences.cpp moc_About.cpp moc_SqlWriterThread.cpp moc_SqlWriter.cpp moc_PlaceholderLineEdit.cpp moc_qtsoap.cpp moc_Mantis.cpp moc_ChangelogWindow.cpp moc_Launchpad.cpp
moc_MainWindow.cpp: MainWindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

moc_maiaXmlRpcServerConnection.cpp: libmaia/maiaFault.h \
		libmaia/maiaXmlRpcServerConnection.h
	/usr/bin/moc $(DEFINES) $(INCPATH) libmaia/maiaXmlRpcServerConnection.h -o moc_maiaXmlRpcServerConnection.cpp

moc_maiaXmlRpcServer.cpp: libmaia/maiaObject.h \
		libmaia/maiaXmlRpcServerConnection.h \
		libmaia/maiaFault.h \
		libmaia/maiaXmlRpcServer.h
	/usr/bin/moc $(DEFINES) $(INCPATH) libmaia/maiaXmlRpcServer.h -o moc_maiaXmlRpcServer.cpp

moc_maiaXmlRpcClient.cpp: libmaia/maiaObject.h \
		libmaia/maiaXmlRpcClient.h
	/usr/bin/moc $(DEFINES) $(INCPATH) libmaia/maiaXmlRpcClient.h -o moc_maiaXmlRpcClient.cpp

moc_maiaObject.cpp: libmaia/maiaObject.h
	/usr/bin/moc $(DEFINES) $(INCPATH) libmaia/maiaObject.h -o moc_maiaObject.cpp

moc_maiaFault.cpp: libmaia/maiaFault.h
	/usr/bin/moc $(DEFINES) $(INCPATH) libmaia/maiaFault.h -o moc_maiaFault.cpp

moc_Backend.cpp: SqlWriterThread.h \
		trackers/Backend.h
	/usr/bin/moc $(DEFINES) $(INCPATH) trackers/Backend.h -o moc_Backend.cpp

moc_Bugzilla.cpp: trackers/Backend.h \
		SqlWriterThread.h \
		libmaia/maiaXmlRpcClient.h \
		libmaia/maiaObject.h \
		trackers/Bugzilla.h
	/usr/bin/moc $(DEFINES) $(INCPATH) trackers/Bugzilla.h -o moc_Bugzilla.cpp

moc_NewTracker.cpp: NewTracker.h
	/usr/bin/moc $(DEFINES) $(INCPATH) NewTracker.h -o moc_NewTracker.cpp

moc_NovellBugzilla.cpp: trackers/Bugzilla.h \
		trackers/Backend.h \
		SqlWriterThread.h \
		libmaia/maiaXmlRpcClient.h \
		libmaia/maiaObject.h \
		trackers/NovellBugzilla.h
	/usr/bin/moc $(DEFINES) $(INCPATH) trackers/NovellBugzilla.h -o moc_NovellBugzilla.cpp

moc_Autodetector.cpp: Autodetector.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Autodetector.h -o moc_Autodetector.cpp

moc_SqlBugModel.cpp: SqlBugModel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) SqlBugModel.h -o moc_SqlBugModel.cpp

moc_SqlBugDelegate.cpp: SqlBugDelegate.h
	/usr/bin/moc $(DEFINES) $(INCPATH) SqlBugDelegate.h -o moc_SqlBugDelegate.cpp

moc_CommentFrame.cpp: CommentFrame.h
	/usr/bin/moc $(DEFINES) $(INCPATH) CommentFrame.h -o moc_CommentFrame.cpp

moc_UploadDialog.cpp: UploadDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) UploadDialog.h -o moc_UploadDialog.cpp

moc_Preferences.cpp: Preferences.h
	/usr/bin/moc $(DEFINES) $(INCPATH) Preferences.h -o moc_Preferences.cpp

moc_About.cpp: About.h
	/usr/bin/moc $(DEFINES) $(INCPATH) About.h -o moc_About.cpp

moc_SqlWriterThread.cpp: SqlWriterThread.h
	/usr/bin/moc $(DEFINES) $(INCPATH) SqlWriterThread.h -o moc_SqlWriterThread.cpp

moc_SqlWriter.cpp: SqlWriter.h
	/usr/bin/moc $(DEFINES) $(INCPATH) SqlWriter.h -o moc_SqlWriter.cpp

moc_PlaceholderLineEdit.cpp: PlaceholderLineEdit.h
	/usr/bin/moc $(DEFINES) $(INCPATH) PlaceholderLineEdit.h -o moc_PlaceholderLineEdit.cpp

moc_qtsoap.cpp: qtsoap/qtsoap.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qtsoap/qtsoap.h -o moc_qtsoap.cpp

moc_Mantis.cpp: trackers/Backend.h \
		SqlWriterThread.h \
		trackers/Mantis.h
	/usr/bin/moc $(DEFINES) $(INCPATH) trackers/Mantis.h -o moc_Mantis.cpp

moc_ChangelogWindow.cpp: ChangelogWindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) ChangelogWindow.h -o moc_ChangelogWindow.cpp

moc_Launchpad.cpp: trackers/Backend.h \
		SqlWriterThread.h \
		trackers/Launchpad.h
	/usr/bin/moc $(DEFINES) $(INCPATH) trackers/Launchpad.h -o moc_Launchpad.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		graphics/arrow_up.png \
		graphics/spinner-big.gif \
		graphics/accept.png \
		graphics/changelog.png \
		graphics/search.png \
		graphics/entomologist-32.png \
		graphics/stop.png \
		graphics/arrow_refresh.png \
		graphics/bug.png
	/usr/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_MainWindow.h ui_NewTracker.h ui_CommentFrame.h ui_UploadDialog.h ui_Preferences.h ui_About.h ui_ChangelogWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MainWindow.h ui_NewTracker.h ui_CommentFrame.h ui_UploadDialog.h ui_Preferences.h ui_About.h ui_ChangelogWindow.h
ui_MainWindow.h: MainWindow.ui \
		PlaceholderLineEdit.h
	/usr/bin/uic MainWindow.ui -o ui_MainWindow.h

ui_NewTracker.h: NewTracker.ui \
		PlaceholderLineEdit.h
	/usr/bin/uic NewTracker.ui -o ui_NewTracker.h

ui_CommentFrame.h: CommentFrame.ui
	/usr/bin/uic CommentFrame.ui -o ui_CommentFrame.h

ui_UploadDialog.h: UploadDialog.ui
	/usr/bin/uic UploadDialog.ui -o ui_UploadDialog.h

ui_Preferences.h: Preferences.ui
	/usr/bin/uic Preferences.ui -o ui_Preferences.h

ui_About.h: About.ui
	/usr/bin/uic About.ui -o ui_About.h

ui_ChangelogWindow.h: ChangelogWindow.ui
	/usr/bin/uic ChangelogWindow.ui -o ui_ChangelogWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp About.h \
		ChangelogWindow.h \
		Preferences.h \
		UploadDialog.h \
		CommentFrame.h \
		SqlBugDelegate.h \
		SqlBugModel.h \
		trackers/Bugzilla.h \
		trackers/Backend.h \
		SqlWriterThread.h \
		libmaia/maiaXmlRpcClient.h \
		libmaia/maiaObject.h \
		trackers/NovellBugzilla.h \
		trackers/Launchpad.h \
		trackers/Mantis.h \
		NewTracker.h \
		MainWindow.h \
		Autodetector.h \
		ui_MainWindow.h \
		PlaceholderLineEdit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

maiaXmlRpcServerConnection.o: libmaia/maiaXmlRpcServerConnection.cpp libmaia/maiaXmlRpcServerConnection.h \
		libmaia/maiaFault.h \
		libmaia/maiaXmlRpcServer.h \
		libmaia/maiaObject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maiaXmlRpcServerConnection.o libmaia/maiaXmlRpcServerConnection.cpp

maiaXmlRpcServer.o: libmaia/maiaXmlRpcServer.cpp libmaia/maiaXmlRpcServer.h \
		libmaia/maiaObject.h \
		libmaia/maiaXmlRpcServerConnection.h \
		libmaia/maiaFault.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maiaXmlRpcServer.o libmaia/maiaXmlRpcServer.cpp

maiaXmlRpcClient.o: libmaia/maiaXmlRpcClient.cpp libmaia/maiaXmlRpcClient.h \
		libmaia/maiaObject.h \
		libmaia/maiaFault.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maiaXmlRpcClient.o libmaia/maiaXmlRpcClient.cpp

maiaObject.o: libmaia/maiaObject.cpp libmaia/maiaObject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maiaObject.o libmaia/maiaObject.cpp

maiaFault.o: libmaia/maiaFault.cpp libmaia/maiaFault.h \
		libmaia/maiaObject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maiaFault.o libmaia/maiaFault.cpp

Backend.o: trackers/Backend.cpp trackers/Backend.h \
		SqlWriterThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Backend.o trackers/Backend.cpp

Bugzilla.o: trackers/Bugzilla.cpp trackers/Bugzilla.h \
		trackers/Backend.h \
		SqlWriterThread.h \
		libmaia/maiaXmlRpcClient.h \
		libmaia/maiaObject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bugzilla.o trackers/Bugzilla.cpp

NewTracker.o: NewTracker.cpp NewTracker.h \
		ui_NewTracker.h \
		PlaceholderLineEdit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewTracker.o NewTracker.cpp

NovellBugzilla.o: trackers/NovellBugzilla.cpp trackers/NovellBugzilla.h \
		trackers/Bugzilla.h \
		trackers/Backend.h \
		SqlWriterThread.h \
		libmaia/maiaXmlRpcClient.h \
		libmaia/maiaObject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NovellBugzilla.o trackers/NovellBugzilla.cpp

Autodetector.o: Autodetector.cpp libmaia/maiaXmlRpcClient.h \
		libmaia/maiaObject.h \
		trackers/NovellBugzilla.h \
		trackers/Bugzilla.h \
		trackers/Backend.h \
		SqlWriterThread.h \
		trackers/Launchpad.h \
		trackers/Mantis.h \
		Autodetector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Autodetector.o Autodetector.cpp

SqlBugModel.o: SqlBugModel.cpp SqlBugModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SqlBugModel.o SqlBugModel.cpp

SqlBugDelegate.o: SqlBugDelegate.cpp SqlBugDelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SqlBugDelegate.o SqlBugDelegate.cpp

CommentFrame.o: CommentFrame.cpp CommentFrame.h \
		ui_CommentFrame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CommentFrame.o CommentFrame.cpp

UploadDialog.o: UploadDialog.cpp UploadDialog.h \
		ui_UploadDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UploadDialog.o UploadDialog.cpp

Preferences.o: Preferences.cpp Preferences.h \
		ui_Preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Preferences.o Preferences.cpp

About.o: About.cpp About.h \
		ui_About.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o About.o About.cpp

SqlWriterThread.o: SqlWriterThread.cpp SqlWriterThread.h \
		SqlWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SqlWriterThread.o SqlWriterThread.cpp

SqlWriter.o: SqlWriter.cpp SqlWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SqlWriter.o SqlWriter.cpp

PlaceholderLineEdit.o: PlaceholderLineEdit.cpp PlaceholderLineEdit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PlaceholderLineEdit.o PlaceholderLineEdit.cpp

qtsoap.o: qtsoap/qtsoap.cpp qtsoap/qtsoap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtsoap.o qtsoap/qtsoap.cpp

Mantis.o: trackers/Mantis.cpp qtsoap/qtsoap.h \
		trackers/Mantis.h \
		trackers/Backend.h \
		SqlWriterThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mantis.o trackers/Mantis.cpp

ChangelogWindow.o: ChangelogWindow.cpp ChangelogWindow.h \
		ChangelogListDelegate.h \
		ui_ChangelogWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChangelogWindow.o ChangelogWindow.cpp

ChangelogListDelegate.o: ChangelogListDelegate.cpp ChangelogListDelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChangelogListDelegate.o ChangelogListDelegate.cpp

Launchpad.o: trackers/Launchpad.cpp trackers/Launchpad.h \
		trackers/Backend.h \
		SqlWriterThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Launchpad.o trackers/Launchpad.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_maiaXmlRpcServerConnection.o: moc_maiaXmlRpcServerConnection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maiaXmlRpcServerConnection.o moc_maiaXmlRpcServerConnection.cpp

moc_maiaXmlRpcServer.o: moc_maiaXmlRpcServer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maiaXmlRpcServer.o moc_maiaXmlRpcServer.cpp

moc_maiaXmlRpcClient.o: moc_maiaXmlRpcClient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maiaXmlRpcClient.o moc_maiaXmlRpcClient.cpp

moc_maiaObject.o: moc_maiaObject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maiaObject.o moc_maiaObject.cpp

moc_maiaFault.o: moc_maiaFault.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maiaFault.o moc_maiaFault.cpp

moc_Backend.o: moc_Backend.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Backend.o moc_Backend.cpp

moc_Bugzilla.o: moc_Bugzilla.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Bugzilla.o moc_Bugzilla.cpp

moc_NewTracker.o: moc_NewTracker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NewTracker.o moc_NewTracker.cpp

moc_NovellBugzilla.o: moc_NovellBugzilla.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NovellBugzilla.o moc_NovellBugzilla.cpp

moc_Autodetector.o: moc_Autodetector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Autodetector.o moc_Autodetector.cpp

moc_SqlBugModel.o: moc_SqlBugModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SqlBugModel.o moc_SqlBugModel.cpp

moc_SqlBugDelegate.o: moc_SqlBugDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SqlBugDelegate.o moc_SqlBugDelegate.cpp

moc_CommentFrame.o: moc_CommentFrame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CommentFrame.o moc_CommentFrame.cpp

moc_UploadDialog.o: moc_UploadDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UploadDialog.o moc_UploadDialog.cpp

moc_Preferences.o: moc_Preferences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Preferences.o moc_Preferences.cpp

moc_About.o: moc_About.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_About.o moc_About.cpp

moc_SqlWriterThread.o: moc_SqlWriterThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SqlWriterThread.o moc_SqlWriterThread.cpp

moc_SqlWriter.o: moc_SqlWriter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SqlWriter.o moc_SqlWriter.cpp

moc_PlaceholderLineEdit.o: moc_PlaceholderLineEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PlaceholderLineEdit.o moc_PlaceholderLineEdit.cpp

moc_qtsoap.o: moc_qtsoap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtsoap.o moc_qtsoap.cpp

moc_Mantis.o: moc_Mantis.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Mantis.o moc_Mantis.cpp

moc_ChangelogWindow.o: moc_ChangelogWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ChangelogWindow.o moc_ChangelogWindow.cpp

moc_Launchpad.o: moc_Launchpad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Launchpad.o moc_Launchpad.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install_translations: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/entomologist/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/entomologist/ 
	-$(INSTALL_FILE) /home/work/entomologist/entomologist_en.qm $(INSTALL_ROOT)/usr/share/entomologist/


uninstall_translations:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/entomologist/entomologist_en.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/entomologist/ 


install_icon32: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/32x32/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/32x32/apps/ 
	-$(INSTALL_FILE) /home/work/entomologist/install_icons/32x32/entomologist.png $(INSTALL_ROOT)/usr/share/icons/hicolor/32x32/apps/


uninstall_icon32:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/32x32/apps/entomologist.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/32x32/apps/ 


install_icon64: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/ 
	-$(INSTALL_FILE) /home/work/entomologist/install_icons/64x64/entomologist.png $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/


uninstall_icon64:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/entomologist.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/ 


install_icon128: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/ 
	-$(INSTALL_FILE) /home/work/entomologist/install_icons/128x128/entomologist.png $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/


uninstall_icon128:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/entomologist.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/ 


install_desktop: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /home/work/entomologist/entomologist.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktop:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/entomologist.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install:  install_translations install_icon32 install_icon64 install_icon128 install_desktop  FORCE

uninstall: uninstall_translations uninstall_icon32 uninstall_icon64 uninstall_icon128 uninstall_desktop   FORCE

FORCE:

